### ISSUE TITLE
wont convert for me.

### ISSUE THREAD

**Issue by gh-doot** [timothycrosley/jiphy#33]
/##########################################################\
 ............................................................
 ...................................................... .....
 ...7$$$$.............$$$$$........MM.M:.MMMM. M,..M:MM .MM..
 .I$I~~=~$$.7M$$$M$7$$?====$$......MM.M:.M...M.M,..M: M .M ..
 I$~~~~~~~$NZ$$$$$$8$=~~~~~~~$.....MM.M:.MMMMM.MMMMM:..MM ...
 $=~~~~~~=$$$M$$$NZ$$7~=~~~~~=$.MM.MM.M:.M.....M,..M:..MM....
 7~~~~~~~$$$/_$$$_\$$$~~~~~~==$. MMO .M:.M ....M,..M:..MM....
 $~~~~~~~$$$$$Z$$Z7$$$=~~~~~~~$..............................
 $=~~~~~~$$$$$$$$$$$$$=~~~~~~$.. ....... ....................
  $$~~~~~$$|$$$$$$$$|$~~~~=$.7777777...... ..................
 ...$$$$$$$M\$$$$$$/M$$$$$7,$77777777:..YOUR CLIENTSIDE DONE.
 . .......$$D\$$$$/M$~. ..=777777777?.... .. ........ .......
 ...........,7$$$$$7777777777777..................... .......
 ..............777777777777777......... ............... .....
 ...............77777777777................VERSION 1.2.2.....
 ........ ...................................................
 ............................................................
 \##########################################################/

 Copyright (C) 2015 Timothy Edmund Crosley
 Under the MIT License

Traceback (most recent call last):
  File "C:\Users\*\AppData\Local\Programs\Python\Python38-32\Scripts\jiphy-script.py", line 11, in <module>
    load_entry_point('jiphy==1.2.2', 'console_scripts', 'jiphy')()
  File "c:\users\*\appdata\local\programs\python\python38-32\lib\site-packages\jiphy\main.py", line 115, in main
    input_code = input_file.read()
  File "c:\users\*\appdata\local\programs\python\python38-32\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 3255: character maps to <undefined>

**Comment by gh-doot** [comment]
also the code is
```
#Packages
import transcrypt
import jiphy
import os
from os import system, name
import shutil
from tqdm import tqdm
import time
import requests
#System Commands
#THEY WERE A FAILURE! PLEASE DO NOT USE! THEY WILL NOT DO ANYTHING!
#def createfile(filename, filedata, var):
#    with open(filename, 'w') as var:
#        var.write(filedata)
#        print('Created file ' + filename + ' with ' + filedata + " and it's variable name is" + var + '.')
#def deletefile(path):
#    os.remove(path)
#def deletedirectory(path):
#    os.rmdir(path)
#def createdirectory(path):
#    os.mkdir(path)
#def movefile(file, folder):
#    shutil.move(file, folder)
#def existsfile(file):
#    os.path.isfile(file)
#def existsdir(folder):
#    os.path.isdir(folder)
#Variables
readme = 'README.txt'
source = "ProjectFiles.rar"
destination = "Apps"
#README Creation
if os.path.isfile(readme) == False:
    with open(readme, 'w') as fp:
        fp.write("! Please credit ThisIsACoolBoy (Zayan The Minecraft Coder and Gamer in YT) also note this only works in WiFi. !")
else:
    pass
#Custom Commands
def cls(sleeptime):
    time.sleep(sleeptime)
    if name == 'nt':
        _ = system('cls')
    else:
        _ = system('clear')    
#def directory():
#    if name == 'nt':
#        _ = system('dir/s')
#    else:
#        _ = system('ls')
#Below is part of the troll.
def finished(message, author):
    print(message)
    print('And is made by ' + author + '.')
# This was only for the youtube video.
# Activate if you want...  
#PART 1 (Fetching requests, absolutely fake.)
print('Fetching request man UuU')
with tqdm(total=100) as pbar:
    for i in range(100):
        time.sleep(0.01)
        pbar.update(1)
print('Sending requests!')
with tqdm(total=1000,unit='KB') as pbar:
    for i in range(1000):
        time.sleep(0.001)
        pbar.update(1)        
#PART 2 (Real installation!)
chunk_size = 1024
url = "https://drive.google.com/uc?export=download&id=1MlUkK7Ce-H8hW1t6rTjgXEBzDkLY-dyS"
r = requests.get(url, stream = True)
total_size = int(r.headers['content-length'])
with open("ProjectFiles.rar", 'wb') as f:
    for data in tqdm(iterable=r.iter_content(chunk_size=chunk_size), total = total_size/chunk_size, unit='KB'):
        f.write(data)
#PART 3 (Download.)        
print('Installation Complete! Now downloading!')
if os.path.isdir(destination) == True:
    if os.path.isfile(destination + '/' + source) == True:
        os.remove(destination + '/' + source)
    else:
        os.rmdir(destination)
        os.mkdir(destination)
        shutil.move(source, destination)
        cls(3)
if os.path.isdir(destination) == False:
    os.mkdir(destination)
    shutil.move(source, destination)
if os.path.isfile(destination + '/' + source) == True:
    print('Successfully downloaded!')
    print('Please wait while we create the logs!')
    with open('logs.txt', 'w') as log:
        log.write('| Hey! | ')
        log.write('Install success?: True | ')
        log.write('Passed?: True | ')
        log.write('Is not 3rd party?: True | ')
        log.write('Is given by zayan kiddy?: True | ')
        log.write('Is having README?: True | ')
        log.write('Ís using windows?: True | ')
        log.write('Installing repository files... | ')
        log.write('Installation passed?: True | ')
        log.write('Is new?: True | ')
        log.write('Is well known and is from zayan kiddy?: True for zayan kiddy and false for well known. | ')
        log.write('CODE: 0x817271 | ')
        log.write('If you dont know what the code means. Ask zayan kiddy. | ')
else:
    print('Failed!')
    with open('logs.txt', 'w') as log:
        log.write('| Hey! | ')
        log.write('Install success?: False | ')
        log.write('Passed?: False | ')
        log.write('Is not 3rd party?: True | ')
        log.write('Is given by zayan kiddy?: True | ')
        log.write('Is having README?: True | ')
        log.write('Ís using windows?: null | ')
        log.write('Installing repository files... | ')
        log.write('Installation passed?: False | ')
        log.write('Is new?: True | ')
        log.write('Is well known and is from zayan kiddy?: True for zayan kiddy and false for well known. | ')
        log.write('CODE: 0x000001 | ')
        log.write('If you dont know what the code means. Ask zayan kiddy. | ')
finished('Download has been finished, See the result in the folder the python file was, the folder the result is on is Apps', 'zayan kiddy')
print('Before we go... Let us do something please..')
print('hah just kidding bro.')
cls(5)
print('...')
cls(5)
print('Please wait, We will shortly bring data...')

```

**Comment by gh-doot** [comment]
i know.. its big,

**Comment by ThisIsACoolBoy** [comment]
5 hrs w/o an answer yet.

**Comment by retsimx** [comment]
You might have a unicode problem fren.

**Comment by retsimx** [comment]
15 mins w/o an answer yet.

**Comment by gh-doot** [comment]
How could I fix that
