### ISSUE TITLE
rise gbk error

### ISSUE THREAD

**Issue by xxller** [timothycrosley/jiphy#36]
Traceback (most recent call last):
  File "D:\pycharm_project\github\jiphy\venv\Scripts\jiphy-script.py", line 33, in <module>
    sys.exit(load_entry_point('jiphy==1.2.2', 'console_scripts', 'jiphy')())
  File "D:\pycharm_project\github\jiphy\venv\lib\site-packages\jiphy-1.2.2-py3.9.egg\jiphy\main.py", line 115, in main
UnicodeDecodeError: 'gbk' codec can't decode byte 0xac in position 69453: illegal multibyte sequence

**Comment by Eleven1202** [comment]
me too

**Comment by Eleven1202** [comment]
你可以试试
import jiphy

with open("bundles.js", "r", encoding="utf-8") as fp:
    exec_js = fp.read()
jiphy.to.python(exec_js)
